### ISSUE TITLE
Can't add user because castopod can't send email

### ISSUE THREAD

**Issue by clawfire** [YunoHost-Apps/castopod_ynh#100]
### Describe the bug

After a fresh install, I wanted to add my first podcast producer user. Got 
> Désolé, il y a eu un problème lors de l&#039;envoi de l&#039;email. Nous ne pouvons pas envoyer un email à &quot;[EMAIL REDACTED FOR CONFIDENTIALITY]&quot;

(yes with those unescaped char ^^) 

### Context

- Hardware: Gandi VPS
- YunoHost version: 11.2.3
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- Make a fresh install and follow post install steps
- Go to User section
- Try to create a new user

### Expected behavior

User is created and an email is sent to that user

**Comment by ericgaspar** [comment]
Upgrading to the last version 1.6.5 should fix email and can be tested:
```
sudo yunohost app upgrade castopod -u https://github.com/YunoHost-Apps/castopod_ynh/tree/testing
```

**Comment by clawfire** [comment]
I would love to but I have an error `packaging.version.InvalidVersion: Invalid version: '1.1.2~ynh2'`. Can't get my catalog listing either since the last os package update.

**Comment by clawfire** [comment]
hum ... I ran the command and the upgrade went well but then there's a LOT of errors in the server happening. I gonna try to restart the webserver.

My castopod instance is here https://podcast.djs.lu/

**Comment by orhtej2** [comment]
Updated 1.6.5 released, mail support is in progress.

**Comment by clawfire** [comment]
> Upgrading to the last version 1.6.5 should fix email and can be tested:
> 
> ```
> sudo yunohost app upgrade castopod -u https://github.com/YunoHost-Apps/castopod_ynh/tree/testing
> ```

Now I used this, can't upgrade using YNH web interface. Any tips on how to return to some state that can be managed by YNH ?

**Comment by orhtej2** [comment]
Why can't you? Can you please share logs if the upgrade is failing?

**Comment by clawfire** [comment]
Sure thing. Full log [can be found here](https://paste.yunohost.org/raw/wawejaleja)

My guess is this cause the issue: 

```
2024-01-02 21:32:46,265: DEBUG - [mysqli_sql_exception]
2024-01-02 21:32:46,265: DEBUG - 
2024-01-02 21:32:46,265: DEBUG - Table 'cp_media' already exists
2024-01-02 21:32:46,266: DEBUG - 
2024-01-02 21:32:46,266: DEBUG - at SYSTEMPATH/Database/MySQLi/Connection.php:306
```

I gonna make a backup and try to reinstall castopod, then apply the backup. We'll see.

**Comment by orhtej2** [comment]
What you're describing is not how backups work unfortunately (backup actually reinstalls the app, so it's impossible to apply backup on top of existing app), I'll try to repro the issue and work around it.

**Comment by orhtej2** [comment]
Can you try running as `root`:

```sh
sudo -u postgres psql --dbname=castopod --command="UPDATE cp_migrations SET class='Media\\\\Database\\\\Migrations\\\\AddMedia', namespace='Media' where class='App\\\\Database\\\\Migrations\\\\AddMedia'"
```

Does this report smth along the lines of '1 row updated'? If so, can you try running upgrade from web admin again?

**Comment by clawfire** [comment]
The backup didn't restore the postgres database :( so got a "no database nammed castopod" 😢 

I gonna reinstall it all

**Comment by orhtej2** [comment]
I'm sorry to hear that :/

You didn't create a backup prior to uninstalling, did you?

**Comment by clawfire** [comment]
Reopening because the latest version has broken email sending again so I cannot add use >.>

**Comment by orhtej2** [comment]
That is strange, local mail setup was always broken, but why is it with external vendor? Any logs? What conf (roughly) are you using?

**Comment by clawfire** [comment]
Here's my config file 

```
#--------------------------------------------------------------------
# Example Environment Configuration file
# 
# This file can be used as a starting point for
# your castopod instance settings.
#
# For manual configuration:
#   - copy this file's contents to a file named `.env`
#   - replace all the default settings with your values
#   - go to `/cp-install` to complete installation
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Instance configuration
#--------------------------------------------------------------------
app.baseURL="https://podcast.djs.lu/"
media.baseURL="https://podcast.djs.lu/"
admin.gateway="admin"
auth.gateway="auth"

media.root="media"
media.storage="/home/yunohost.app/castopod"

#--------------------------------------------------------------------
# Database configuration
#--------------------------------------------------------------------
database.default.hostname="localhost"
database.default.database="castopod"
database.default.username="castopod"
database.default.password="[PASSWORD]"
database.default.DBPrefix="cp_"

#--------------------------------------------------------------------
# Email configuration
#--------------------------------------------------------------------
email.fromEmail="no-reply@podcast.djs.lu"
email.fromName="DJs.lu podcast"
email.SMTPHost="smtp.postmarkapp.com"
email.SMTPPort="25"
email.SMTPUser="[USER]"
email.SMTPPass="[PASSWORD]"
email.SMTPCrypto="tls"

#--------------------------------------------------------------------
# Cache configuration (advanced)
#
# Keep as is if you don't know what this means
#--------------------------------------------------------------------
cache.handler="file"

#--------------------------------------------------------------------
# Redis configuration
#--------------------------------------------------------------------
cache.handler="redis"
cache.redis.host="127.0.0.1"
cache.redis.password=null
cache.redis.port=6379
cache.redis.database=1

#--------------------------------------------------------------------
# S3 configuration
#--------------------------------------------------------------------
media.fileManager="s3"
media.s3.endpoint="podcastdjslu"
media.s3.key="[KEY]"
media.s3.secret="[SECRET]"
media.s3.region="eu-central-1"

#--------------------------------------------------------------------
# REST API configuration
#--------------------------------------------------------------------
# restapi.enabled=true
# restapi.basicAuthUsername=castopod
# restapi.basicAuthPassword=password
# restapi.basicAuth=true
```

**Comment by orhtej2** [comment]
The e-mail config seems OK. Are you sure the credentials you're passing are valid? Are you able to use these successfully with 'normal' e-mail client?

**Comment by clawfire** [comment]
They are the one I used before reinstalling castopod so yes :/

*Milan Thibault*
📝 clawfire.net ( http://clawfire.net/ ) • 🐦 @clawfire ( https://twitter.com/clawfire ) • 🗣 he/him
🧘🏻  Not urgent? consider writing me a ponymail ( https://ponymessenger.com/invite/RGVVFQ ) then

📱 I made a web app that lets you store your EU Covid Digital Certificate into your phone wallets. It’s free, ad-free, tracking-free, open-source. Try it now ( https://covid19passbook.netlify.app/ ) !

**Comment by maxlinux2000** [comment]
Hi, this bug still occurs on 1.11.0~ynh1 version just installed.

tnx
MaX

**Comment by ImaCrea** [comment]
Hi there,

I installed a clean fresh install today and it seems mail doesn't work out of the box.

I find a way by creating a user `mailbot` and then go into castpod's .env and edit it myself :

```
#--------------------------------------------------------------------
# Email configuration
#--------------------------------------------------------------------
email.fromEmail="mailbot@mydomain.tld"
email.fromName="Castopod"
email.SMTPHost="mydomain.tld"
email.SMTPPort="587"
email.SMTPUser="mailbot"
email.SMTPPass="XXXXX"
email.SMTPCrypto="tls"
```

Hope it helps

**Comment by clawfire** [comment]
Things is, at the next update, I believe the env variables will be cleared 😭

**Comment by ImaCrea** [comment]
> Things is, at the next update, I believe the env variables will be cleared 😭

Just upgraded and in deed I had to re-edit it. So be careful and copy it before doing the update.

**Comment by FatherMcGruder** [comment]
> Hi there,
> 
> I installed a clean fresh install today (1.12.11) and it seems mail doesn't work out of the box.
> 
> I found a way by creating a user `mailbot` and then go into castpod's .env and edit it myself :
> 
> ```
> #--------------------------------------------------------------------
> # Email configuration
> #--------------------------------------------------------------------
> email.fromEmail="mailbot@mydomain.tld"
> email.fromName="Castopod"
> email.SMTPHost="mydomain.tld"
> email.SMTPPort="587"
> email.SMTPUser="mailbot"
> email.SMTPPass="XXXXX"
> email.SMTPCrypto="tls"
> ```
> 
> Hope it helps

I feel like I should know this, but what directory contains the .env file usually?

**Comment by orhtej2** [comment]
> I feel like I should know this, but what directory contains the .env file usually?

`/var/www/castopod`, easily accessible by running `yunohost app shell castopod` which opens a shell exactly there
