### ISSUE TITLE
Upgrade to 1.4

### ISSUE THREAD

**Issue by bishopgodsey** [YunoHost-Apps/castopod_ynh#101]
Is there a chance we might get an upgrade of this app to the most recent version?

**Comment by kamazeuci** [comment]
would be awesome! in order to federate with mastodon instances that have Safe Mode on.

**Comment by brayozz** [comment]
Now it's 1.6.5 , but they don't give AF. This the biggest downside of yunohost.

**Comment by ericgaspar** [comment]
@brayozz Yes we give a fuck. But If you know how to fix https://github.com/YunoHost-Apps/castopod_ynh/pull/99 you are welcome.
the downside of YunoHost is also dealing with people who take volunteer work for granted.

**Comment by lapineige** [comment]
You mean the downside of relying on other people work is that you don't need to do it yourself ? Interesting 🤔

Help is always appreciated, and things won't be magically solved.

**Comment by kamazeuci** [comment]
thanks to all the developers for their work. A lot of us are indeed grateful and considerate for your efforts, please forget those who aren't. Hope all you knowledgeable people find a way to make the build successfully. thanks.

**Comment by DDRrayray2012** [comment]
I would also like to say thank you to the developers for their work here.   Keep up the good work and ignore those that post negativity.   The vast majority of us understand that this is volunteer work and appreciate all that you do!

**Comment by benjaminbellamy** [comment]
Thank you to everyone (kudos to @ericgaspar) working here for making Castopod available on YunoHost.  
We do give a f**k. A lot.  
🫶

**Comment by orhtej2** [comment]
@ericgaspar I'm getting somewhere with #102, but e-mail config is borked and breaks `upgrade`. Shall we just set it to `$app@$domain` ?

**Comment by ericgaspar** [comment]
Upgrading to the last version 1.6.5 can be tested:
```
sudo yunohost app upgrade castopod -u https://github.com/YunoHost-Apps/castopod_ynh/tree/testing
```

**Comment by 0utl4w** [comment]
I tried to update, but it broke my installation. Today I installed the castopod version provided in the yunohost gui (1.1.2?). Then I did the setup and created a podcast, uploaded 2 Episodes and it worked well. Then I tried your upgrade tonthe test version and afterwards there was only this "Whooops"-page but nothing else. Couldn't enter the admin page either. So I restored the old version.

**Comment by DDRrayray2012** [comment]
I upgraded from 1.1.2 to the latest 1.6.5 (I did mind the upgrade warning that it wouldn't work upgrading from beta) and it didn't work for my installation.  I restored from backup back to 1.1.2.   I may rebuild my castopod from a fresh install of 1.6.5 (which is fairly easy with only 24 episodes and castopod allows you to backdate publishing dates).  Again, I appreciate everything the ynh developers do here for people like me who are complete noobs to things like this.  You make getting things like this up and running super easy!

**Comment by brayozz** [comment]
> @brayozz Yes we give a fuck. But If you know how to fix https://github.com/YunoHost-Apps/castopod_ynh/pull/99 you are welcome.
> 
> the downside of YunoHost is also dealing with people who take volunteer work for granted.

Apologies for my previous post. I was not aware of yunohost being ran by volunteers. I'm a total noob when it comes to self-hosting and Yunohost is preventing me from getting gray hair so early. Keep the awesome work.

If you wish to check the outcome, on bccloud.online I've installed the test version of castopod-ynh on the clean "prod" version of castopod available on yunohost. No errors during update via terminal.

**Comment by kamazeuci** [comment]
thanks to everyone for the work and love shared. I am also a noob. Is it safe now to update castopod inside yunohost then?

**Comment by orhtej2** [comment]
@kamazeuci while back out strategy exists (restore pre-upgrade backup) preliminary results do not look promising. I'd wait.

**Comment by DDRrayray2012** [comment]
> When it fails, before restoring a backup if you can share (via YunoPaste for instance) the log of the service, it could help a lot to diagnose what's the issue ! 😉

Here’s the log from when i tried updating tonight.  And the site isn’t displaying correctly (and logging in isn’t working either)

https://paste.yunohost.org/raw/sokifoziqa

**Comment by 0utl4w** [comment]
I just made a fresh virgin install of the test-release. Problem is now that the config dialogue doesn't appear on first visit and even though I selected a user in yunohost gui to admin castopod I cannot login.

You find the log here: https://paste.yunohost.org/raw/opereciyos

**Comment by 0utl4w** [comment]
I did a nother try. Uninstalled 1.6.5 and I installed v 1.1.2 freshly. After installation of 1.1.2 I did the install setup, everything went well. Then I did the upgrade to 1.6.5 and after it didn't work anymore.

Here is the log: https://paste.yunohost.org/raw/jayexihuna

**Comment by 0utl4w** [comment]
Oh and for some reason the upgrade script just deletes the old pre-upgrade-backup from my castopod instance that used to work... not good.

**Comment by lapineige** [comment]
> > @brayozz Yes we give a fuck. But If you know how to fix #99 you are welcome.
> > the downside of YunoHost is also dealing with people who take volunteer work for granted.
> 
> Apologies for my previous post. I was not aware of yunohost being ran by volunteers. I'm a total noob when it comes to self-hosting and Yunohost is preventing me from getting gray hair so early. Keep the awesome work.

Thanks for the apologies, it's always appreciated. For a future occasion, in the absence of knowledge, a little more caution in formulations and assumptions about the project would be welcome 🙂


> If you wish to check the outcome, on bccloud.online I've installed the test version of castopod-ynh on the clean "prod" version of castopod available on yunohost. No errors during update via terminal.

Cool thanks for the feedback :)
In my case, the page appears to have broken layout (huge logo, almost no content).

**Comment by lapineige** [comment]
> thanks to everyone for the work and love shared. I am also a noob. Is it safe now to update castopod inside yunohost then?

Upgrading to a testing branch is always risky, even if backups are automatically made (and if you could make some), that's no guaranty it won't fail or worse break something. So it's better not to do it on a production environment, except if you can take the risk.
That said, depending on feedback on some testing branch, you can determine how likely it is to work or break :)

**Comment by lapineige** [comment]
> Oh and for some reason the upgrade script just deletes the old pre-upgrade-backup from my castopod instance that used to work... not good.

The number "-1" and number "-2" too ? It is supposed to replace the older one first, then the other one, and so on.

**Comment by 0utl4w** [comment]
> > Oh and for some reason the upgrade script just deletes the old pre-upgrade-backup from my castopod instance that used to work... not good.
> 
> The number "-1" and number "-2" too ? It is supposed to replace the older one first, then the other one, and so on.

It actually deleted the 1 and the 2 was created, so there eas no "-1", but maybe I was too quick, didn't check if the 2 contains the data from my working setup. Sorry

**Comment by orhtej2** [comment]
@0utl4w yeah it's always best to make proper backup, automatic pre-upgrade backups roll and only the latest one is preserved.

@lapineige problem is 1.6.5 was [merged to `master` already](https://github.com/YunoHost-Apps/castopod_ynh/pull/99)🐛

**Comment by ericgaspar** [comment]
and the email settings from the `.env` are not working 🥶

**Comment by ericgaspar** [comment]
I am also considering using the `data_dir` path  to store the media folder but if not transitioned properly thinks will break even more

**Comment by brayozz** [comment]
@lapineige 
> 
> cool thanks for the feedback :)
> 
> In my case, the page appears to have broken layout (huge logo, almost no content).

Somehow part of my message disappeared. I have the exact same outcome - huge logo, broken ui after test upgrade.

**Comment by ericgaspar** [comment]
You can set CI_ENVIRONMENT="development" in your  .env file (in the root folder /var/www/castopod/.env) to know more about the error.

**Comment by lapineige** [comment]
And probably reload the service after changing the `.env` file, right ?

**Comment by ewagoner** [comment]
I upgraded using the admin panel and it broke all my pages. The error I'm getting is "Could not retrieve podcast cover" and I get this for each of my podcasts and the admin page. Googling that message returns zero hits -- haven't seen that in a while.

I tried restoring the backup via the control panel, but that is giving "The following apps can't be restored because they are already installed: castopod" so now I'm stuck. Is there a manual way to restore the backup?

**Comment by lapineige** [comment]
You need to remove castopod (the broken one) before restoring.

**Comment by orhtej2** [comment]
Call for testers, take 2. This time upgrade from v1.1.2 **should** work and resulting v1.6.5 **should** properly serve all the media.

Previous broken state looks partially like an upstream bug.

To test please **create proper backup (pre-upgrade backups are rolling hence I consider them unreliable)**, then run `yunohost app upgrade castopod -u https://github.com/orhtej2/castopod_ynh/tree/installupgrade`

Please report any issues you encounter.

**Comment by DDRrayray2012** [comment]
> Call for testers, take 2. This time upgrade from v1.1.2 **should** work and resulting v1.6.5 **should** properly serve all the media.
> 
> Previous broken state looks partially like an upstream bug.
> 
> To test please **create proper backup (pre-upgrade backups are rolling hence I consider them unreliable)**, then run `yunohost app upgrade castopod -u https://github.com/orhtej2/castopod_ynh/tree/installupgrade`
> 
> Please report any issues you encounter.

Tried the update today and it seemed to work.   The only issue I ran into is not being able to log in with my usual email/password combination.  I wasn't sure what might have caused the issue, so I reverted back to my backup of 1.1.2, just to be safe.    But the site and everything else seemed to work as it normally does.

**Comment by orhtej2** [comment]
Thanks for checking, I'll have a look at the login issue I guess

**Comment by orhtej2** [comment]
@ DDRrayray2012 This is an [upstream change](https://github.com/codeigniter4/shield/blob/develop/UPGRADING.md#version-100-beta3-to-100-beta4), we can bypass that I guess.

Or fix the mail x_x

**Comment by orhtej2** [comment]
You should be able to log in with old credentials now. You can try again with

```sh
$ sudo yunohost app upgrade castopod -u https://github.com/orhtej2/castopod_ynh/tree/installupgrade
```

**Comment by brayozz** [comment]
> You should be able to log in with old credentials now. You can try again with
> 
> ```shell
> $ sudo yunohost app upgrade castopod -u https://github.com/orhtej2/castopod_ynh/tree/installupgrade
> ```

Clean install of 1.1.2 ynh version via Yunohost, upgrade through your link before completing cp-install steps, everything seems to work.

**Comment by DDRrayray2012** [comment]
> You should be able to log in with old credentials now. You can try again with
> 
> ```shell
> $ sudo yunohost app upgrade castopod -u https://github.com/orhtej2/castopod_ynh/tree/installupgrade
> ```

Just did the upgrade...and I can indeed log in!   Looks like everything is working properly now!   Thanks for all the hard work on this!

**Comment by DDRrayray2012** [comment]
And bonus for the upgrade to 1.6.5...  The soundbite feature now works (which never worked properly for me previously, which I think was an issue with Castopod, not anything you all worked on) just like I expected it too!  Very nice!

**Comment by orhtej2** [comment]
1.6.5 released 🤞

**Comment by 0utl4w** [comment]
> 1.6.5 released 🤞

Great work! Thanks for your effort!
