### ISSUE TITLE
Error when creating a new podcast, 1.6.5_ynh1

### ISSUE THREAD

**Issue by brayozz** [YunoHost-Apps/castopod_ynh#112]
### Describe the bug

*Error when creating a new podcast*

### Context

- Hardware: *Oracle free tier VPS, 4 CPU, 24 GB ram*
- YunoHost version: 11.2.5
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 1.6.5_ynh1
### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to 'Castopod admin panel'*
   2. *Click on 'Add new podcast'*
   3. *Click save 'after filling necessary data'*
   4. *See error*

### Expected behavior

Podcast should be created.

### Logs

ErrorException: mkdir(): Permission denied in /var/www/castopod/modules/Media/FileManagers/FS.php:30
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /var/www/castopod/modules/Media/FileManagers/FS.php(30): mkdir()
#2 /var/www/castopod/modules/Media/Entities/Image.php(151): Modules\Media\FileManagers\FS->save()
#3 /var/www/castopod/modules/Media/Entities/Image.php(101): Modules\Media\Entities\Image->saveSizes()
#4 /var/www/castopod/modules/Media/Models/MediaModel.php(120): Modules\Media\Entities\Image->saveFile()
#5 /var/www/castopod/app/Entities/Podcast.php(258): Modules\Media\Models\MediaModel->saveMedia()
#6 /var/www/castopod/vendor/codeigniter4/framework/system/Entity/Entity.php(483): App\Entities\Podcast->setCover()
#7 /var/www/castopod/vendor/codeigniter4/framework/system/Entity/Entity.php(150): CodeIgniter\Entity\Entity->__set()
#8 /var/www/castopod/vendor/codeigniter4/framework/system/Entity/Entity.php(131): CodeIgniter\Entity\Entity->fill()
#9 /var/www/castopod/modules/Admin/Controllers/PodcastController.php(213): CodeIgniter\Entity\Entity->__construct()
#10 /var/www/castopod/modules/Admin/Controllers/PodcastController.php(47): Modules\Admin\Controllers\PodcastController->attemptCreate()
#11 /var/www/castopod/vendor/codeigniter4/framework/system/CodeIgniter.php(918): Modules\Admin\Controllers\PodcastController->_remap()
#12 /var/www/castopod/vendor/codeigniter4/framework/system/CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController()
#13 /var/www/castopod/vendor/codeigniter4/framework/system/CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest()
#14 /var/www/castopod/public/index.php(85): CodeIgniter\CodeIgniter->run()
#15 {main}

<img width="732" alt="image" src="https://github.com/YunoHost-Apps/castopod_ynh/assets/25374150/b2c428a1-beae-4720-8915-509048c1775d">

**Comment by orhtej2** [comment]
This workaround should work for now: https://github.com/YunoHost-Apps/castopod_ynh/issues/110#issuecomment-1791678944

**Comment by orhtej2** [comment]
Fixed in 1.6.5~2
