### ISSUE TITLE
Image and audio files not loading after yunohost system upgrade

### ISSUE THREAD

**Issue by DDRrayray2012** [YunoHost-Apps/castopod_ynh#117]
![The Double Dutch Rudder Podcast (@ddrpodcast) • Activity](https://github.com/YunoHost-Apps/castopod_ynh/assets/109685395/90c2acb1-0f48-4233-a38b-964fb498059e)

### Describe the bug

After upgrade of libnhttp2-14, files not longer load on castopod site

### Context

- Hardware: Dell Optiplex 9020
- YunoHost version: 11.2.7 (stable)
- I have access to my server: webadmin/ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

### Expected behavior

After an upgrade of yunohost system package libnhttp2-14 and upgrade of castopod from 1.6.5~ynh2 to 1.7.1~ynh1, images and audio files are no longer accessible on https://ddrpodcast.com.   Admin panel is still accessible.  Problem is still present even if restoring back to 1.6.5.

### Logs
From yunohost update
https://paste.yunohost.org/raw/habajenopu

From castopod update
https://paste.yunohost.org/raw/sufociliti

**Comment by orhtej2** [comment]
Thanks for flagging, I reverted the release.

Core issue is `/home/yunohost.app/castopod/media` is **not** owned by `www-data` group, will investigate WTF I broke the last time around.

**Comment by DDRrayray2012** [comment]
Ok.   Anything i need to do to get things on my site working again or should i just wait for the next update?  I’m ok either way.
