### ISSUE TITLE
Installer cp-install misses fields admin_gateway and auth_gateway

### ISSUE THREAD

**Issue by pintman** [YunoHost-Apps/castopod_ynh#133]
### Describe the bug

When running the command https://my-website/cp-install, only the fields for "Hostname" and "Media Base" are shown, but not the fields for "admin_gateway" and "auth_gateway". So I cannot fill in the required data and am getting an error when I am trying to continue the installation of castopod.

### Context

- Hardware: *VPS bought online*
- YunoHost version: fresh install current version
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

**Comment by orhtej2** [comment]
What error are you getting? In my experience clicking 'Next' takes you to admin creation eventually.

**Comment by pintman** [comment]
An error message occurs at the top saying that fields 
"admin_gateway" and "auth_gateway" are missing. It does not continue but stays on the same page.

**Comment by orhtej2** [comment]
Can you try clicking on the 'Next' button again?

**Comment by pintman** [comment]
Did you change anything? I tried clicking multiple times with no visible effect.

**Comment by orhtej2** [comment]
No, but my experience was that you needed to click `Next' twice on first
page for some reason.

**Comment by pintman** [comment]
I think the hint string (for me in german) in the input forms field in the instance_config.php produces the problem. I contains some "-characters.

After removing this I get the complete input form and can continue.

**Comment by orhtej2** [comment]
This issue was reported upstream as well as I can see: https://code.castopod.org/adaures/castopod/-/issues/412

**Comment by pintman** [comment]
That's correct. Unfortunately I am not able to post a hint for the solution there: wasn't able to register. Further I didn't get an answer to  my related [mastodon post](https://chaos.social/@pintman/111733107640297706). :(

**Comment by pintman** [comment]
Reported upstream. 

https://code.castopod.org/adaures/castopod/-/issues/412

**Comment by orhtej2** [comment]
As [commented upstream](https://code.castopod.org/adaures/castopod/-/issues/412#note_14596) change locale (language preferences) to English to circumvent the issue (for now).

**Comment by orhtej2** [comment]
I'm closing this one as it's an upstream issue properly tracked.
