### ISSUE TITLE
Error when creating a podcast: Whoops! We seem to have hit a snag. Please try again later...

### ISSUE THREAD

**Issue by TestDesk** [YunoHost-Apps/castopod_ynh#18]
Hello,

the following error occurred when creating a podcast(Podcasts > New Podcast):

**Whoops!
We seem to have hit a snag. Please try again later...**

YH version: 4.1.8 (stable)
Castopod version: 1.0.0-41~ynh1
Installation on a subdomain
Browser: Firefox 88.0
OS: macOS Catalina 10.15.7

Installation of Castopod went without errors.
All required fields when creating the podcast were filled in. 
Diagnosis of YH shows no errors.
Another browser has been tried (Safari 14.0.3)

All relevant browser plugins have been switched off (uBlock Origin, Bitdefender Anti-Tracker).

Have I overlooked something?

THX

![Bildschirmfoto 2021-04-25 um 22 38 48](https://user-images.githubusercontent.com/55596230/116009021-80c84800-a617-11eb-95b5-feede78a5df0.png)

**Comment by ericgaspar** [comment]
You can set `CI_ENVIRONMENT="development"` in your ` .env` file (in the root folder `/var/www/castopod/.env`) to know more about the error.

**Comment by TestDesk** [comment]
THX @ericgaspar,
![Bildschirmfoto 2021-04-26 um 01 58 12](https://user-images.githubusercontent.com/55596230/116013930-09081680-a633-11eb-8c8e-c7f3896eb56b.png)
 

here is the result

**Comment by TestDesk** [comment]
I think there is a BUG here. The field is optional, not mandatory.
![Bildschirmfoto 2021-04-26 um 02 07 49](https://user-images.githubusercontent.com/55596230/116014246-a6177f00-a634-11eb-9fd4-df86839009f8.png)

**Comment by benjaminbellamy** [comment]
This bug was solved in Castopod alpha-42. (You're using alpha-41)
Sorry for the inconvenience.
A simple workaround on this version is to add a tag such as 
```
<podcast:licence url="http://creativecommons.org/licenses/by-nd/4.0/">(CC BY-NC-ND 4.0)</podcast:licence>
```

**Comment by ericgaspar** [comment]
@TestDesk 
You can also try to install Castopod version 53 from testing branch: 
`sudo yunohost app install https://github.com/YunoHost-Apps/castopod_ynh/tree/testing`
We still have some issue while upgrading from previous versions but a new install should work find.

**Comment by TestDesk** [comment]
> A simple workaround on this version is to add a tag such as
> 
> ```
> <podcast:licence url="http://creativecommons.org/licenses/by-nd/4.0/">(CC BY-NC-ND 4.0)</podcast:licence>
> ```
@benjaminbellamy 
Thanks for the info. It works.

**Comment by TestDesk** [comment]
> You can also try to install Castopod version 53 from testing branch:
> `sudo yunohost app install https://github.com/YunoHost-Apps/castopod_ynh/tree/testing`
> We still have some issue while upgrading from previous versions but a new install should work fine.

Hello @ericgaspar,

i have installed and tested it. After the second installation it worked. Thanks.

When will the YunoHost package be updated for a 1 click installation. And to which version? 

THX
