### ISSUE TITLE
/!\ Alpha 55 upgrade

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/castopod_ynh#19]
:warning: Due to significant structural changes in the database, this version may require several manual actions to migrate from alpha 41 to 55 (see Can't access public page and others (seems related to activitypub module) (#115) · Issues · Podlibre / Castopod Host · GitLab)
It is advisable to do a new installation.

**Comment by MonsieurPoutounours** [comment]
Direct link to the issue in their Gitlab for people who want to do the "manual" thing : https://code.podlibre.org/podlibre/castopod-host/-/issues/115

**Comment by ImaCrea** [comment]
In deed I tried to go upgrade from testing branch to master and I had a few issues appearing. I guess I'm gonna need to re-do a manual update.
