### ISSUE TITLE
App failed on CI, probably unix permission issue

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/castopod_ynh#21]
https://ci-apps.yunohost.org/ci/job/999

```
2021/05/12 00:09:14 [error] 5968#5968: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: The .env file is not readable: /var/www/castopod/.env
```

**Comment by benjaminbellamy** [comment]
Have you run `/cp-install` on your browser?

**Comment by ericgaspar** [comment]
Seems like the post install is not working anymore... 
https://github.com/YunoHost-Apps/castopod_ynh/blob/1d8a44c6e7146f9f590ae61e471551bc2358a433/scripts/install#L127-L129 
@kay0u If I can bother you once again with this issue (I don't know why the settings you proposed are not working anymore  -.° )...

**Comment by kay0u** [comment]
```
chown -R $app: $final_path
```
Should be called before curl now (because of recent changes of setup_source I guess)

**Comment by ericgaspar** [comment]
> ```
> chown -R $app: $final_path
> ```
> 
> Should be called before curl now (because of recent changes of setup_source I guess)

@kay0u Thanks again, that fixes the issue
