### ISSUE TITLE
Feature Request: Use Redis Server instead of File as cache system

### ISSUE THREAD

**Issue by benjaminbellamy** [YunoHost-Apps/castopod_ynh#25]
### Feature Request

castopod_ynh is currently using file cache system which is not the fastest in town. Since Redis is already up&running, why not use it?

### Context

- Hardware: *Raspberry Pi 4*
- YunoHost version: *YunoHost 4.1.7.2*
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *1.0.0-57~ynh1*
- If upgrading, current package version: n/a

### Steps to reproduce

```sh
    cat /var/www/castopod/.env
```

```
    […]
    # Cache configuration (advanced)
    # Keep as is if you don't know what this means
    cache.handler="file"
```

### Expected behavior

```
    […]
    #--------------------------------------------------------------------
    # Redis configuration
    #--------------------------------------------------------------------
    cache.handler="redis"
    cache.redis.host="127.0.0.1"
    cache.redis.password=null
    cache.redis.port=6379
    cache.redis.database=0
```

### Logs

N/A

**Comment by ericgaspar** [comment]
Closing with #27
