### ISSUE TITLE
Castop just issued an update. How can I use it?

### ISSUE THREAD

**Issue by unklebonehead** [YunoHost-Apps/castopod_ynh#39]
Castopod just pushed an update to fix an import issue that I need. Can you push it through or is there a way I can implment it on my install? I desperately need this as well as a few other people I know.

https://code.podlibre.org/podlibre/castopod-host/-/releases/v1.0.0-alpha.69

**Comment by ericgaspar** [comment]
Version 69 is now on the testing branch #40 and should be pushed to master tomorrow after the CI tests.

**Comment by unklebonehead** [comment]
Sweet thank you!

**Comment by unklebonehead** [comment]
They also say I may need to clear the redis cache. How do you do that on Yunohost. I did a reboot. does that do it?

**Comment by ericgaspar** [comment]
> They also say I may need to clear the redis cache. How do you do that on Yunohost. I did a reboot. does that do it?

in a terminal : `redis-cli -n [database number] flushdb` where the database number is the one set in the config file `/var/www/castopod/.env` around  L.37
