### ISSUE TITLE
Cannot log in as admin after install

### ISSUE THREAD

**Issue by mattbk** [YunoHost-Apps/castopod_ynh#46]
### Describe the bug

After I install the app using yunohost web interface or command line and go to `domain.ltd/cp-admin`, I cannot log in.

If I use the yunohost account defined as admin during install, the message is 
> Unable to log you in. Please check your password. 

If I use another username, the message is 
>Unable to log you in. Please check your credentials. 

Password, whether the one associated with that user account or the admin password defined during installation, doesn't seem to work.

### Context

- Hardware: Old x64 PC
- YunoHost version: 4.2.6.1 (stable)
- I have access to my server: Through SSH, through the webadmin, and direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: both main (through web interface) and testing branch (command line)

### Steps to reproduce
- `sudo yunohost app install https://github.com/YunoHost-Apps/castopod_ynh/tree/testing --debug`
- https://domain.tld/cp-admin
- try to log in
- password does not work

### Expected behavior

Password works and I can log in.

### Logs

https://paste.yunohost.org/raw/wununebofa

**Comment by lenowac** [comment]
same thing for me, but my password generator generated `Vaseline3+Abacus+Grievous` and neither do `Vaseline`, `Vaseline3` or `Vaseline3AbacusGrievous` work.

**Comment by schmidthausen** [comment]
I tried using a simple password and it still doesn't work. ynh v. 11.0.9.15 app v.1.0.0-99~ynh2

**Comment by demitasse-1** [comment]
I am having this issue. I just updated my castopod to  1.0.4~ynh1 and am unable to login or send a login link. I get the "whoops hit a snag" page. I deleted the installation and restored from a back up and am having the same problem. Any suggestions on how to troubleshoot this? I have a simple password without special characters or spaces
