### ISSUE TITLE
Unable to open config-panel after installation

### ISSUE THREAD

**Issue by sphinxc0re** [YunoHost-Apps/castopod_ynh#56]
### Describe the bug

After I installed the app via the web interface, I tried to access the config panel via the yunohost webadmin. When clicking on the button that should lead to the panel, after a while I get an error message:

```
Error: "500" Internal Server Error

Action: "GET" /yunohost/api/apps/castopod/config-panel?full&locale=de

Error message:
Config panel question 'free_footprint' should be initialized with a value during install or upgrade.
```

### Context

- Hardware: Beefy DO droplet
- YunoHost version: `4.3.6.2 (stable)`
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: `1.0.0-80~ynh1`

### Steps to reproduce

1. install Castopod from the web admin
2. go to applications -> castopod
3. click on the button that leads to the config panel

### Expected behavior

I would expect the config panel to show up and let me configure my instance

### Logs

https://paste.yunohost.org/raw/ocivavukin

![image](https://user-images.githubusercontent.com/3702016/151131723-e90ec071-b1fa-427c-9737-13d22819c897.png)

**Comment by mattbk** [comment]
Does your instance work? Did you go through the admin setup at the URL you set?

**Comment by sphinxc0re** [comment]
Somehow the admin setup didn't work previously. Now it works... somehow 🤔
