### ISSUE TITLE
Castopod foes not federate

### ISSUE THREAD

**Issue by AppleOnTech** [YunoHost-Apps/castopod_ynh#67]
--- 

### Describe the bug

Posts from the instance are not federated. 

### Context

- Hardware: Linode VPS 1core 2gb ram
- YunoHost version: 4.3.6.3 (stable).
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

Follow the Castopod instance from a mastodon account. 
Post from Castopod
Look on other account to see if post showed up. 
It does not, though under followers on outside account, it shows Castopod and gives post count, but you don't see them. 

### Expected behavior

For post to show up on outside fedi instance, mastodon, etc... for people to see it and be able to comment n it.

**Comment by ericgaspar** [comment]
#70 should fix the issue
