### ISSUE TITLE
php8.1 required for v1.0.0

### ISSUE THREAD

**Issue by oceanlover-yuno** [YunoHost-Apps/castopod_ynh#80]
### Describe the bug

After installing the current testing branch, the domain/cp-install page gives this error message:
*Your PHP version must be 8.1 or higher to run CodeIgniter. Current version: 8.0.24*

### Context

- Hardware: *Proxmox VM*
- YunoHost version: 11.0.10.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: testing
### Steps to reproduce
    ```sh
    sudo yunohost app install https://github.com/Yunohost-Apps/castopod-ynh/tree/testing
    ```
### Expected behavior

*php8.1 would be installed as a dependency.*

**Comment by ericgaspar** [comment]
Fixed with #78
