### ISSUE TITLE
Error php version after update to 1.0.0~ynh1

### ISSUE THREAD

**Issue by rthees** [YunoHost-Apps/castopod_ynh#81]
After updating the Castopod-App to version 1.0.0~ynh1, my castopod-site doesn't work anymore, only this error appears:

`Your PHP version must be 8.1 or higher to run CodeIgniter. Current version: 8.0.24`

How to fix this? My Yunohost-version: 11.0.10.1 (stable).

**Comment by xplosionmind** [comment]
Hello, I do not really understand how to fix this issue, though. I am experiencing the same trouble.

**Comment by xplosionmind** [comment]
Still relevant in version 1.0.2~ynh_1

**Comment by xplosionmind** [comment]
Still happening in 1.0.3~ynh1. This is what I see now:

![Screenshot 2022-11-19 at 11 37 23 AM](https://user-images.githubusercontent.com/42862428/202846606-9157e1b3-4e49-4129-9949-6bb2d80c6554.jpg)

**Comment by Tagadda** [comment]
@xplosionmind Still happening when you upgrade to 1.1.2~ynh2 ?
Can you provide some logs + the nginx config file ?

**Comment by xplosionmind** [comment]
> @xplosionmind Still happening when you upgrade to 1.1.2~ynh2 ?

I uninstalled the app and reinstalled it from scratch. I still see the “Whoops!” page…

How can I provide the app logs?

Content of `/etc/nginx/conf.d/sconnesso.link.d/castopod.conf`:

```
#sub_path_only rewrite ^/$ / permanent;
location / {

  # Path to source
  alias /var/www/castopod/public/;

  index index.php;

  client_max_body_size 512M;

  more_clear_headers 'X-Frame-Options';

  try_files $uri $uri/ /index.php;
  location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    fastcgi_pass unix:/var/run/php/php8.1-fpm-castopod.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param REMOTE_USER $remote_user;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $request_filename;
  }

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}
```

**Comment by Tagadda** [comment]
> I still see the “Whoops!” page…

On which page ? Can you browse https://sconnesso.link/ ?

> How can I provide the app logs?

Usually you can find those in `/var/log/`. Maybe `/var/log/php8.1-fpm.log` and `/var/log/nginx/sconnesso.link-error.log`
