### ISSUE TITLE
Upgrade to 1.0.1~ynh1 results in Your PHP version must be 8.1 or higher to run CodeIgniter. Current version: 8.0.25

### ISSUE THREAD

**Issue by DDRrayray2012** [YunoHost-Apps/castopod_ynh#84]
### Describe the bug

After upgrading to 1.0.1~ynh1, the following statement comes up when navigating to castopod instance "Your PHP version must be 8.1 or higher to run CodeIgniter. Current version: 8.0.25".

### Context

- Hardware: Raspberry PI 3b
- YunoHost version: 11.1.0.2 (testing)
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

### Expected behavior

Upgrade to the current version of ynh castopod version with normal access function.

**Comment by mattbk** [comment]
Allegedly closed after https://github.com/YunoHost-Apps/castopod_ynh/issues/80, but I'm hitting the same issue tonight.

**Comment by xplosionmind** [comment]
I am having the same problem…

**Comment by EssmannMa** [comment]
same error when updating to 1.0.2~ynh1

**Comment by xplosionmind** [comment]
I confirm: still relevant in version 1.0.2~ynh1

**Comment by rthees** [comment]
Same here.

**Comment by xplosionmind** [comment]
Still happening in 1.0.3~ynh1. This is what I see now:

![Screenshot 2022-11-19 at 11 37 23 AM](https://user-images.githubusercontent.com/42862428/202846606-9157e1b3-4e49-4129-9949-6bb2d80c6554.jpg)

**Comment by rthees** [comment]
After upgrading to 1.0.3~ynh1, frontend is running fine.
But when i log in the backend, i also get the "Whoops!" screen.

**Comment by DDRrayray2012** [comment]
Same with mine.   I tested using both username and email on version 1.0.0-99~ynh2 and both worked fine but on 1.0.3~ynh1, which requires using email to log in, i get the whoops screen noted above.

**Comment by EssmannMa** [comment]
the same after update to 1.0.4ynh1

**Comment by rthees** [comment]
confirmed: after updating to 1.0.4ynh1 the castopod-frontend is working. But when i log in the backend, the "Whooops"-Error appears again.

**Comment by EssmannMa** [comment]
the same after update to 1.0.5ynh1

**Comment by DDRrayray2012** [comment]
I can confirm rthees comment above.   I'm also getting the Whoops error after trying to login with email.

**Comment by DDRrayray2012** [comment]
Same issue is still present in the 1.1.0~ynh1 update

**Comment by DDRrayray2012** [comment]
looks like it's still an issue with the 1.1.2~ynh1 update.

**Comment by xplosionmind** [comment]
Hi @ericgaspar, is there any update or any fix planned? We would really appreciate it! ❤️

**Comment by ericgaspar** [comment]
Nobody as posted logs in this issue. We need logs.

**Comment by xplosionmind** [comment]
> We need logs.

Sorry… There you go @ericgaspar: the following is the browser console log I see when visiting `https://sconnesso.link`, my Castopod installation. Any other logs I could give you? I do not know where to retrieve them.

```
15:40:14.779 GEThttps://sconnesso.link/
[HTTP/2 500 Internal Server Error 96ms]

15:40:15.085 GEThttps://sconnesso.link/ynh_portal.js
[HTTP/2 404 Not Found 44ms]

15:40:15.086 GEThttps://sconnesso.link/ynh_overlay.css
[HTTP/2 404 Not Found 44ms]

15:40:15.087 GEThttps://sconnesso.link/ynhtheme/custom_portal.js
[HTTP/2 404 Not Found 56ms]

15:40:15.089 GEThttps://sconnesso.link/ynhtheme/custom_overlay.css
[HTTP/2 404 Not Found 53ms]

15:40:15.140 The resource from “https://sconnesso.link/ynh_portal.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). sconnesso.link
15:40:15.140 The resource from “https://sconnesso.link/ynh_overlay.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). sconnesso.link
15:40:15.143 Loading failed for the <script> with source “https://sconnesso.link/ynh_portal.js”. sconnesso.link:11:1
15:40:15.170 The resource from “https://sconnesso.link/ynhtheme/custom_overlay.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). sconnesso.link
15:40:15.173 The resource from “https://sconnesso.link/ynhtheme/custom_portal.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). sconnesso.link
15:40:15.174 Loading failed for the <script> with source “https://sconnesso.link/ynhtheme/custom_portal.js”. sconnesso.link:11:1
15:40:15.176 GEThttps://sconnesso.link/ynh_overlay.css
[HTTP/2 404 Not Found 30ms]

15:40:15.231 The resource from “https://sconnesso.link/ynh_overlay.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). sconnesso.link
15:40:15.234 GEThttps://sconnesso.link/ynhtheme/custom_overlay.css
[HTTP/2 404 Not Found 30ms]

15:40:15.279 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:396
15:40:15.293 The resource from “https://sconnesso.link/ynhtheme/custom_overlay.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). sconnesso.link
```

**Comment by ericgaspar** [comment]
can you add `CI_ENVIRONMENT=development` in the `.env` file and restart service to get the full log message?

**Comment by xplosionmind** [comment]
Could you please indicate me better where I could get the full log message?

In the meanwhile, I changed the `.env` file within the Castopod directory like this:

```
#--------------------------------------------------------------------
# Example Environment Configuration file
# 
# This file can be used as a starting point for
# your castopod instance settings.
#
# For manual configuration:
#   - copy this file's contents to a file named `.env`
#   - replace all the default settings with your values
#   - go to `/cp-install` to complete installation
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Instance configuration
#--------------------------------------------------------------------
app.baseURL="https://sconnesso.link/"
app.mediaBaseURL="https://sconnesso.link/"
admin.gateway="admin"
auth.gateway="auth"

#--------------------------------------------------------------------
# Database configuration
#--------------------------------------------------------------------
database.default.hostname="localhost"
database.default.database="castopod"
database.default.username="castopod"
database.default.password="wdJqAuEI6WqWbaePBlDyXdgD"
database.default.DBPrefix="cp_"

#--------------------------------------------------------------------
# Redis configuration
#--------------------------------------------------------------------
cache.handler="redis"
cache.redis.host="127.0.0.1"
cache.redis.password=null
cache.redis.port=6379
cache.redis.database=1
analytics.salt="kGX3O4!=iE>uTirqH#<{!Okasga+X&RB*dn)8D3xxXSeCIQyJNK16DCe~0;74(}W"

CI_ENVIRONMENT=development
```

**Comment by ericgaspar** [comment]
if you go to https://sconnesso.link/ your should get error messages displayed

**Comment by xplosionmind** [comment]
> if you go to https://sconnesso.link/ your should get error messages displayed

Oh, ok! Sorry… As you can see yourself, there are several things I do not understand… The screenshots of the page are below, while the saver version on the Wayback Machine is [here](https://web.archive.org/web/20230119160048/https://sconnesso.link/). For simplicity, I also saved a Markdown version, [here](https://paste.yunohost.org/jovohequke.md)


<img width="1440" alt="Screenshot 2023-01-19 at 16 55 58" src="https://user-images.githubusercontent.com/42862428/213490845-ed81f798-1f15-4a21-8192-fbf973ad6aec.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 56 06" src="https://user-images.githubusercontent.com/42862428/213490852-4ba6c99a-4834-4031-bab0-ce2168236ff6.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 56 17" src="https://user-images.githubusercontent.com/42862428/213490855-ccb869ea-6b49-4e38-a18b-66a8109c0fee.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 56 26" src="https://user-images.githubusercontent.com/42862428/213490860-6ed758c9-bb72-4516-a679-78ee39d1db84.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 56 33" src="https://user-images.githubusercontent.com/42862428/213490868-4c6af8f3-dddb-4a30-9d49-2fcd4a2f2d57.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 56 50" src="https://user-images.githubusercontent.com/42862428/213491197-bf6bef94-0aa1-4b86-a90e-1e49ff002336.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 56 56" src="https://user-images.githubusercontent.com/42862428/213490904-af1c7800-4c14-4a27-9738-d289b73ab26e.png">
<img width="1440" alt="Screenshot 2023-01-19 at 16 57 06" src="https://user-images.githubusercontent.com/42862428/213490914-165cce8c-1c63-48ff-b8f6-0a9612edc457.png">

**Comment by DDRrayray2012** [comment]
I stupidly posted mine in the Yunohost forum and not here (apologies for that!).    Here's my info as well.
After upgrading from 1.0.0-99~ynh2 to 1.1.2~ynh1, when I attempt to log in, the website immediately goes to the “Whoops we’ve hit a snag” splash page.

below are the logs from the install:
https://paste.yunohost.org/raw/isayuzodam

Restoring back to 1.0.0-99~ynh2 allows logging in as as expected.

If there's more info you need from me, let me know!

**Comment by xplosionmind** [comment]
Thanks a lot for sharing, @DDRrayray2012! I would love to learn how to roll back to a previous version… could you point me to some documentation or tell me how to do it? Thanks a lot ❤️

**Comment by ericgaspar** [comment]
To give some context. During the beta phase, Castopod added many additions/modifications in the database. YunoHost script did not handle database migration from beta versions to 1.0.0. Thus, some may have missing items in their database.

Now for your unknown column `cp_podcasts.published_at`, we can try this. (this is not tested)

in a terminal:
```
sudo su
```
then
```
source /usr/share/yunohost/helpers
```
then
```
ynh_mysql_execute_as_root --database=castopod --sql=<<'EOF'
SET AUTOCOMMIT = 0;
START TRANSACTION;

ALTER TABLE `cp_settings`
ADD COLUMN context VARCHAR(255) NULL AFTER `type`;

ALTER TABLE cp_podcasts ADD COLUMN published_at DATETIME DEFAULT NULL AFTER 
updated_by;
UPDATE cp_podcasts SET published_at = created_at;
EOF
```

**Comment by DDRrayray2012** [comment]
> Thanks a lot for sharing, @DDRrayray2012! I would love to learn how to roll back to a previous version… could you point me to some documentation or tell me how to do it? Thanks a lot ❤️

when you install an update yunohost does a backup of the current version.   Check your backups to make sure it's there before you do anything!  Once you have, you can uninstall the updated version of castopod and restore the backup in the backups section.

**Comment by xplosionmind** [comment]
Thanks @ericgaspar, I performed the steps you suggested. The output I get is:

```
+ database=castopod
+ '[' -n castopod ']'
+ database=--database=castopod
+ mysql -B --database=castopod
```

**Comment by xplosionmind** [comment]
I rebooted the server. Nothing changes, the error still appears.

**Comment by xplosionmind** [comment]
Hi @ericgaspar, the app is currently flagged as high quality in the catalog, but it is having these great issues… I think this needs to be fixed soon, or to change the flag in the catalog.

**Comment by xplosionmind** [comment]
Hello, the problem is still present in version 1.1.2~ynh2
