### ISSUE TITLE
Post-install setup fails

### ISSUE THREAD

**Issue by narFnarF** [YunoHost-Apps/castopod_ynh#93]
### Describe the bug

After installation, I perform the post-install setup in Castopod and it fails after creating the admin account and setuping the "cp-admin" URLs.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 11.0.10.2 (stable)
- Castopod version: 1.1.2 
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Yes: I have multiple apps installed on multiple domains.
- Using, or trying to install package version/branch: ??
- If upgrading, current package version: ??

### Steps to reproduce
   1. Install Castopod
   2. Open the domain
   3. Fill up the post-install questions
   4. Try to reach the end of the post-install setup.
 
Current result: I can't finish all steps of the post install. I see an error after step 2. If I try to reload, I get a "page not found" error.

### Expected behavior
I can finish the post-install setup.

Note: I was able afterward to manually go to my-domain.tld/cp-admin and login successfully. It's only the post-install that failed for some unknown reason.

**Comment by ericgaspar** [comment]
Just try to install a fresh castopod. I can't reproduce the issue.
