### ISSUE TITLE
Update from 1.0.0-53~ynh1 to 1.1.2~ynh1 

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/castopod_ynh#95]
Hello here,
I'm trying to update from 1.0.0-53ynh1 to 1.1.2ynh1.

With no surprise, the update doesn't go till the end and breaks. It's ok, I don't expect it to work from beta to release 1.0. The fact it's packaged on yunohost is already a beautiful news and allowed us to serve our podcast for more than a year without any worries.

I read on the [Castopod Doc](https://docs.castopod.org/getting-started/update.html) that I should apply updates release by release. I think I'm gonna follow that manual way, through ssh and scp. But I was wondering how would yunohost react to that? I guess I'll have to somehow tell yunohost at some point it's updated, no? Hopefully then I'll be able to follow next package update from the UI?

Thanks for your help :)

**Comment by ericgaspar** [comment]
The main thing that as been evolving during the beta stage is the multiple addition to the database. So if you succeed to upgrade the database you should be able to update from YunoHost.

**Comment by ImaCrea** [comment]
Thank you for your reply @ericgaspar I'll try and let you know here eventually.

**Comment by ImaCrea** [comment]
Hello @ericgaspar I'm writing again as I retried today following your recommandation.

I did step by step the sql script manually from my alpha version till latest 1.7.1. Then I launched the yunohost update. 

But it stops meanwhile with this error :
```
Warning: Variable $redis_db wasn't initialized when trying to replace __REDIS_DB__ in /var/www/castopod/.env
Error: Could not upgrade castopod: An error occurred inside the app upgrade script
Info: The operation 'Upgrade the 'castopod' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20231217-132137-app_upgrade-castopod' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - + for one_var in "${uniques_vars[@]}"
Info: DEBUG - + [[ -v domain ]]
Info: DEBUG - + match_string=__DOMAIN__
Info: DEBUG - + match_string=__DOMAIN__
Info: DEBUG - + replace_string=audiosauti.com
Info: DEBUG - + replace_string=audiosauti.com
Info: DEBUG - + replace_string=audiosauti.com
Info: DEBUG - + sed --in-place s@__DOMAIN__@audiosauti.com@g /var/www/castopod/.env
Info: DEBUG - + for one_var in "${uniques_vars[@]}"
Info: DEBUG - + [[ -v mail_pwd ]]
Info: DEBUG - + match_string=__MAIL_PWD__
Info: DEBUG - + match_string=__MAIL_PWD__
Info: DEBUG - + replace_string=XXXXX (replaced for security)
Info: DEBUG - + replace_string=XXXXX
Info: DEBUG - + replace_string=XXXXX
Info: DEBUG - + sed --in-place s@__MAIL_PWD__@XXXXX@g /var/www/castopod/.env
Info: DEBUG - + for one_var in "${uniques_vars[@]}"
Info: DEBUG - + [[ -v redis_db ]]
Info: DEBUG - + ynh_die '--message=Variable $redis_db wasn'\''t initialized when trying to replace __REDIS_DB__ in /var/www/castopod/.env'
Info: DEBUG - + ynh_exit_properly
Error: The operation 'Upgrade the 'castopod' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20231217-132137-app_upgrade-castopod' to get help
```

I was wondering if you had an idea please about what to do in order to pass this step.

Thanks

**Comment by orhtej2** [comment]
I'll try including this on 1.7.2 upgrade

**Comment by ImaCrea** [comment]
Thanks @orhtej2 🙏

**Comment by orhtej2** [comment]
@ImaCrea can you try upgrading to testing?

`sudo yunohost app upgrade castopod -u https://github.com/YunoHost-Apps/castopod_ynh/tree/testing`

**Comment by ImaCrea** [comment]
Hi @orhtej2 meanwhile I messed up with the server I rebuilt, so I have to start again with the sql scripts and then I'll be able to try this out. When I have time to retry, I'll tell you here eventually. thanks!

**Comment by ImaCrea** [comment]
Hello @orhtej2 I might retry soon. Still from 1.0.0-53~ynh1. So I'll do all the evolution on the database version per version manually following castopod docs and then trigger the castopod update. I'll let you know. ++

**Comment by ImaCrea** [comment]
So... I applied all SQL updates from alpha to beta manually. Then launched the update. Somehow the script couldn't go all the way because apparently of a lack of space, then it reverted itself and.. the app and all its content where gone 😅 Good I'm working on a replicated sandbox instance 😬 (!)

Anyway.. there's been so many changes from this alpha version to the current one. I wasn't really expecting a miracle. I guess I'll have to start from fresh with a clean install and try to import stuff from the original instance onto the new one. I'm just having some doubts on the RSS and URL and link with the plateforms.. will see
