### ISSUE TITLE
Edit Podcast Status

### ISSUE THREAD

**Issue by DDRrayray2012** [YunoHost-Apps/castopod_ynh#98]
### Describe the bug

Clicking "Prevent podcast from being copied" switch and saving produces unknown error and does not identify the error.

### Context

- Hardware: *Raspberry PI 3B*
- YunoHost version: 11.1.13
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- current package version: 1.0.0-99~ynh2

### Steps to reproduce

Clicking "Prevent podcast from being copied" switch and saving produces unknown error and does not identify the error.

### Expected behavior

Being able to change the "Prevent podcast from being copied" switch and saving it.

### Logs

Unable to pull logs specific to castopod.  Application page for castopod within Yunohost also produces an error (see below)
Error: "500"
Action: "GET" /yunohost/api/apps/castopod/config?full&locale=en

Error message:
Config panel question 'free_footprint' should be initialized with a value during install or upgrade.

**Comment by DDRrayray2012** [comment]
Done!   Here's what was output.
[mysqli_sql_exception.pdf](https://github.com/YunoHost-Apps/castopod_ynh/files/10931932/mysqli_sql_exception.pdf)

**Comment by DDRrayray2012** [comment]
If there’s any other info you need, please let me know!  I’m happy to provide whatever you need.

**Comment by ericgaspar** [comment]
did you upgrade from the beta version?

**Comment by DDRrayray2012** [comment]
I'm currently on 1.0.0-beta.19 (1.0.0-99~ynh2) of castopod.   I've tried updating to the 1.1.2~ynh2 version, but when I do, I am unable to log into the cp-admin.   So I've had to restore my backup of the 1.0.0-99~ynh2 version.

**Comment by DDRrayray2012** [comment]
I was actually going to install another instance of Castopod (on a separate domain) and import my current one, but since I had the Prevent podcast from being copied switch turned on, and it's causing an error trying to turn it off and save, I'm a little stuck.

**Comment by DDRrayray2012** [comment]
Is there anything i can do to fix this?  I’d like to migrate the data from this instance of castopodto a fresh install of the current version, but I’m not sure how to do that without being able to import from this instance.

**Comment by DDRrayray2012** [comment]
I was able to delete my previous version of castopod and transfer the episodes to a current version of castopod.   I was able to backdate the schedule publication of the episode and everything seems to be working properly now.   If anyone else needs to do this, just copy your episode information down and install a new instance of castopod and you can re-create your page from there.   Hope this helps.
